module.exports = {
  myNews: [{
    co: 'Apple Inc.',
    sector: 'Technology',
    h: 'Calif. Judge Tosses "Rosen" Suit ',
    s: 'CSR Wire',
    c: 'Apr 09, 2016',
    d: 'Apr 11, 2016',
    i: 13,
    r: 41,
    b: 'Climate and sustainable development expert ClimateCare today announced new impact figures that show it has improved life for 16.5 million people and at the same time...',
    t: 'Business Ethics',
    iss: 'Bribery & Corruption<br />Worker Conditions<br />Safety',
  },{
    co: 'Yelp',
    h: 'U.S. Chamber Foundation Seeks Nominations to Recognize Top Corporate Citizens',
    s: 'CSR Wire',
    c: 'Apr 06, 2016',
    d: 'Apr 10, 2016',
    i: 8,
    r: 15,
    b: 'Climate and sustainable development expert ClimateCare today announced new impact figures that show it has improved life for 16.5 million people and at the same time...',
    t: 'Corruption',
    iss: 'Worker Conditions<br />Safety',
  },{
    co: 'United Airlines',
    h: 'Russian Military Registers Seven Ceasefire Violations in Syria',
    s: 'Bloomberg',
    i: 9,
    r: 33,
    c: 'Apr 02, 2016',
    d: 'Apr 03, 2016',
    b: '',
    t: 'Bribery',
    iss: 'Bribery & Corruption<br />Safety',
  },{
    co: 'Apple Inc.',
    h: 'Gulf markets stabilise, Egypt rebounds',
    s: 'Bloomberg',
    i: 9,
    r: 33,
    c: 'Apr 02, 2016',
    d: 'Apr 03, 2016',
    b: '',
    t: 'Business Ethics',
    iss: 'Safety',
  }],

  articles: [{
    co: 'Apple Inc.',
    sector: 'Technology',
    h: 'Calif. Judge Tosses "Rosen" Suit ',
    s: 'CSR Wire',
    c: 'Apr 09, 2016',
    d: 'Apr 11, 2016',
    i: 13,
    r: 41,
    b: 'Climate and sustainable development expert ClimateCare today announced new impact figures that show it has improved life for 16.5 million people and at the same time...',
    t: 'Business Ethics',
    iss: 'Bribery & Corruption<br />Worker Conditions<br />Safety',
  },{
    co: 'Yelp',
    h: 'U.S. Chamber Foundation Seeks Nominations to Recognize Top Corporate Citizens',
    s: 'CSR Wire',
    c: 'Apr 06, 2016',
    d: 'Apr 10, 2016',
    i: 8,
    r: 15,
    b: 'Climate and sustainable development expert ClimateCare today announced new impact figures that show it has improved life for 16.5 million people and at the same time...',
    t: 'Corruption',
    iss: 'Worker Conditions<br />Safety',
  },{
    co: 'United Airlines',
    h: 'Russian Military Registers Seven Ceasefire Violations in Syria',
    s: 'Bloomberg',
    i: 9,
    r: 33,
    c: 'Apr 02, 2016',
    d: 'Apr 03, 2016',
    b: '',
    t: 'Bribery',
    iss: 'Bribery & Corruption<br />Safety',
  },{
    co: 'Apple Inc.',
    h: 'Gulf markets stabilise, Egypt rebounds',
    s: 'Bloomberg',
    i: 9,
    r: 33,
    c: 'Apr 02, 2016',
    d: 'Apr 03, 2016',
    b: '',
    t: 'Business Ethics',
    iss: 'Safety',
  }],

  company: {
    name: 'Uber Technologies Inc.',
    sector: 'Technology',
    description: '<strong>Uber Technologies Inc.</strong> is an American multinational online transportation network company headquartered in San Francisco, California. It develops, markets and operates the Uber mobile app, which allows consumers with smartphones to submit a trip request which is then routed to Uber drivers who use their own cars. As of April 12, 2016, the service was available in over 60 countries and 404 cities worldwide. Since Uber\'s launch, several other companies have copied its business model, a trend that has come to be referred to as "Uberification".<br /><br />Uber was founded as "UberCab" by Travis Kalanick and Garrett Camp in 2009 and the app was released the following June. Beginning in 2012, Uber expanded internationally. In 2014, it experimented with carpooling features and made other updates. Klout ranked the San Francisco-based company as the 48th-most powerful company in America in 2014. By late-2015, Uber was estimated to be worth $62.5 billion.',
    employees: '1,200',
    address: '1455 Market St<br />San Francisco, CA 94103',
    phone: '(415) 801-4068',
    url: 'http://www.uber.com',
    headquarter: 'United States',
    asset: 'United States',
    revenue: 'Canada',
    rrr: 62.3,
    investor: 47.5,
    corporate: 56.1
  },

  saved: [{
    n: "Lyft",
    s: "Technology",
    rrr: 74,
    peak: 81,
    avg: 62,
  },
  {
    n: "Curb",
    s: "Transportation",
    rrr: 53,
    peak: 77,
    avg: 59,
  },
  {
    n: "Taxi Magic",
    s: "Transportation",
    rrr: 24,
    peak: 51,
    avg: 32,
  },
  {
    n: "Didi Kuaidi",
    s: "Technology",
    rrr: 60,
    peak: 71,
    avg: 62,
  },
  {
    n: "Grab",
    s: "Transportation",
    rrr: 59,
    peak: 66,
    avg: 51,
  },
  {
    n: "Ola",
    s: "Transportation",
    rrr: 94,
    peak: 94,
    avg: 62,
  }],

  watchlist: [{
    n: "Key Competitors",
    co: 6,
    rrr: 71,
    peak: 79,
    avg: 66,
    c: "04/03/2016",
    u: "04/25/2016",
  },{
    n: "Technology Partners",
    co: 31,
    rrr: 52,
    peak: 68,
    avg: 61,
    c: "04/07/2016",
    u: "04/18/2016",
  }],

  search: [{
    name: "American Apparel",
    sector: "Retailer",
    rrr: 77.2,
  },{
    name: "Apple Inc.",
    sector: "Technology",
    rrr: 62.4,
  },{
    name: "Applied Genetic Technologies",
    sector: "Technology",
    rrr: 51.9,
  },{
    name: "Neuberger Berman Holdings LLC",
    sector: "Diversified Financials",
    rrr: 17.2,
  },{
    name: "Huber & Suhner AG",
    sector: "Electrical Equipment",
    rrr: 72.4,
  },{
    name: "Uber Technologies Inc.",
    sector: "Technology",
    rrr: 62.3,
  }],

  issues: [{
    n: "Bribery & Corruption",
    c: 18,
    f: "01/03/2015",
    l: "04/22/2016",
    w: 7,
  },{
    n: "Child Labour",
    c: 11,
    f: "03/19/2016",
    l: "03/28/2016",
    w: 4,
  },{
    n: "Worker Conditions",
    c: 51,
    f: "02/04/2013",
    l: "11/12/2015",
    w: 5,
  },{
    n: "Safety",
    c: 3,
    f: "03/31/2016",
    l: "04/26/2016",
    w: 2,
  }]
};
